[package]
name = "api-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.8", features = ["ws"]}
tower-http = { version = "0.7", features = ["fs"] }
tokio.workspace = true # Асинхронный рантайм
tracing-subscriber.workspace = true
sfu = { path = "../sfu" }
tracing.workspace = true
futures-util.workspace = true
serde_json.workspace = true