[package]
name = "sfu"
version = "0.1.0"
edition = "2024"

[dependencies]
webrtc.workspace = true
tokio.workspace = true # Асинхронный рантайм
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
uuid.workspace = true
flume = { version = "0.12.0", default-features = false, features = ["async", "select"] }
chrono = "0.4"